- name: Deploy Spring Boot app
  hosts: spring_lxc
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Remove existing container if exists (idempotent cleanup)
      shell: |
        docker rm -f test-spring-app || true

    - name: Pull latest app image
      shell: |
        docker pull wnwls1216/test-spring-app:latest

    - name: Run app container
      shell: |
        docker run -d --name test-spring-app -p 8070:8070 wnwls1216/test-spring-app:latest